# Namespace (optional, create or reference existing)
apiVersion: v1
kind: Namespace
metadata:
  name: amazon-prime-video-namespace
---
# Deployment for Amazon Prime Video app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-prime-video-deployment
  namespace: amazon-prime-video-namespace
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: amazon-prime-video
  template:
    metadata:
      labels:
        app: amazon-prime-video
    spec:
      containers:
      - name: amazon-prime-video-container
        image: piotran/devsecops-prime-video:latest  
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Service to expose the Deployment via an AWS Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: amazon-prime-video-service
  namespace: amazon-prime-video-namespace
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # or "alb" if using ALB Ingress
spec:
  type: LoadBalancer
  selector:
    app: amazon-prime-video
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
